#!/bin/bash

# REQUIREMENTS:

# jq - a lightweight and flexible command-line JSON processor.
# https://stedolan.github.io/jq/download/

# Fail if '.entry.sh' does not exist or is empty
if [[ ! -s .entry.sh ]]; then
    echo "ERROR: file '.entry.sh' not found or contains no data." 1>&2
    exit 1
fi

# Fail if 'base.package.json' already exists
if [[ -e base.package.json ]]; then
    echo "ERROR: file 'base.package.json' already exists!" 1>&2
    exit 1
fi

# Generate base package info using variables auto-loaded from entry.sh
echo-file "$HOME/.skeletons/bash/base.package.json" > base.package.json

# Fail if 'base.package.json' does not exist or is empty
if [[ ! -s base.package.json ]]; then
    echo "ERROR: file 'base.package.json' not found or contains no data." 1>&2
    exit 1
fi

# Fail if 'package.json' already exists
if [[ -e package.json ]]; then
    echo "ERROR: file 'package.json' already exists!" 1>&2
    exit 1
fi


# Create new 'package.json' by merging base with packages from dependencies
mkdir -p conf/packages
mv base.package.json conf/packages/__base__.json
init-json-config package.json conf/packages

