#!/bin/bash

# REQUIREMENTS:

# jq - a lightweight and flexible command-line JSON processor.
# https://stedolan.github.io/jq/download/

# Fail if '.eslintrc' already exists
if [[ -e .eslintrc ]]; then
    echo "ERROR: file '.eslintrc' already exists!" 1>&2
    exit 1
fi

# Create new '.eslintrc' by merging modules from 'conf/eslint'
# Using jq array-merge solution from William Langford, 2014, https://github.com/stedolan/jq/issues/502
cat `find -L "conf/eslint" -not -path '*node_modules*' -type f -iname "*.json"` | sed 's://.*::' | jq -s '[.[] | to_entries] | flatten | reduce .[] as $dot ({}; .[$dot.key] += $dot.value)' > ".eslintrc"

