#!/bin/bash

# REQUIREMENTS:

# jq - a lightweight and flexible command-line JSON processor.
# https://stedolan.github.io/jq/download/

# Fail if base.package.json does not exist
if [[ ! -e base.package.json ]]; then
    echo "ERROR: file 'base.package.json' not found." 1>&2
    exit 1
fi

# Fail if package.json already exists
if [[ -e package.json ]]; then
    echo "ERROR: file 'package.json' already exists!" 1>&2
    exit 1
fi

# Create new package.json by merging base with packages from dependencies
# Attribution: Array-merge jq-script courtesy of William Langford
cat "base.package.json" `find -L "conf/packages" -not -path '*node_modules*' -type f -iname "*.json"` | jq -s '[.[] | to_entries] | flatten | reduce .[] as $dot ({}; .[$dot.key] += $dot.value)' > "package.json"

