#!/bin/bash

# REQUIREMENTS:

# jq - a lightweight and flexible command-line JSON processor.
# https://stedolan.github.io/jq/download/

config="tsconfig.json"
modulePath="conf/tsconfig"

# Fail if '.eslintrc' already exists
if [[ -e "$config" ]]; then
    echo "ERROR: file '$config' already exists!" 1>&2
    exit 1
fi

# Create new configuration file by merging modules from module path
# Using jq array-merge solution from William Langford, 2014, https://github.com/stedolan/jq/issues/502
cat `find -L "$modulePath" -not -path '*node_modules*' -type f -iname "*.json"` | sed 's://.*::' | jq -s '[.[] | to_entries] | flatten | reduce .[] as $dot ({}; .[$dot.key] += $dot.value)' > "$config"

